"""update table user

Revision ID: 0f0a30c971b0
Revises: af3de784016d
Create Date: 2021-01-12 00:16:21.705336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f0a30c971b0'
down_revision = 'af3de784016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
