"""buat tabel baru galeri

Revision ID: 77827ede3592
Revises: 3202c9c37977
Create Date: 2021-05-04 07:07:47.249249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77827ede3592'
down_revision = '3202c9c37977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galeri',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('pathname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galeri')
    # ### end Alembic commands ###
